services:
  - type: web
    name: amazonflow-backend
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: PORT
        sync: false